@startuml
actor "Professor"
left to right direction

Professor --> (Show profile info)
Professor --> (Show all professors)
Professor --> (Show all students)
Professor --> (Show all groups)
Professor --> (Show all files)
Professor --> (Show all discussions)
Professor --> (Show all discussion reservations)
Professor --> (Delete discussion)
Professor --> (Create discussion)
Professor --> (Delete discussion reservation)

(Delete discussion) ..> (Create discussion) : <<include>>

@enduml